OC-23589 Update boss-oidc to Update keycloak uid for existing user instead of deleting it
OpenClinica/kpi pull request #134
Opened 2024-12-03 15:48 UTC by gushil

## Checklist

1. [ ] If you've added code that should be tested, add tests
2. [ ] If you've changed APIs, update (or create!) the documentation
3. [ ] Ensure the tests pass
4. [ ] Make sure that your code lints and that you've followed [our coding style](https://github.com/kobotoolbox/kpi/blob/master/CONTRIBUTING.md)
5. [ ] Write a description of your work suitable for publishing on [our forum](https://community.kobotoolbox.org/tag/release-notes)
6. [ ] Mention any related issues in this repository (as #ISSUE) and in other repositories (as kobotoolbox/other#ISSUE)
7. [ ] Open an issue in the [docs](https://github.com/kobotoolbox/docs/issues/new) if there are UI/UX changes

## Description

## Related issues

2024-12-03 22:36 UTC, svadla-oc requested changes

2024-12-03 22:36 UTC, svadla-oc commented on dependencies/pip/dev_requirements.txt
> +-e git+https://github.com/gushil/boss-oidc.git@0eb4478bc8d21edb7289d09d2f43cb1ad0e3c04f#egg=boss-oidc
We should move this repo into OpenClinica organization. I have created a fork from the main repo: https://github.com/OpenClinica/boss-oidc. Could you push your commits into this repo as a new PR?

2024-12-04 14:27 UTC, gushil commented on dependencies/pip/dev_requirements.txt
> +-e git+https://github.com/gushil/boss-oidc.git@0eb4478bc8d21edb7289d09d2f43cb1ad0e3c04f#egg=boss-oidc
Hi @svadla-oc 

PR for OpenClinica/boss-oidc is created in https://github.com/OpenClinica/boss-oidc/pull/1

Thanks.

2024-12-19 21:43 UTC, svadla-oc approved these changes

2024-12-19 21:43 UTC, merged